CREATE SEQUENCE IF NOT EXISTS categoria_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS imagem_produto_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS produto_id_seq START WITH 1 INCREMENT BY 1;
